trydjango18/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    # Examples:
    url(r'^$', 'newsletter.views.home', name='home'),
    url(r'^contact/$', 'newsletter.views.contact', name='contact'),
    url(r'^about/$', 'trydjango18.views.about', name='about'),
    url(r'^ourcontact/$', 'newsletter.views.ourcontact', name='ourcontact'),
    url(r'^productsnservices/$', 'newsletter.views.productsnservices', name='productsnservices'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsletter/models.py
from django.db import models

# Create your models here.
class SignUp(models.Model):
    email = models.EmailField()
    full_name = models.CharField(max_length=100, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self): #Python 3.3 is __str__
        return self.email

newsletter/forms.py
from django import forms
from .models import SignUp


class ContactForm(forms.Form):
    full_name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField()






class SignUpForm(forms.ModelForm):
    class Meta:
        model = SignUp
        fields = ['full_name', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        email_base, provider = email.split("@")
        domain, extension = provider.split('.')
        # if not domain == 'usc':
        #     raise forms.ValidationError("Пожалуйста, убедитесь что вы используете @USC. адрес электронной почты")
        if not extension == "edu":
            raise forms.ValidationError("Пожалуйста, используйте .edu домен")
        return email

    def clean_full_name(self):
        full_name = self.cleaned_data.get('full_name')
        #write validation code
        return full_name

newsletter/views.py
from django.shortcuts import render
from .forms import SignUpForm
from .forms import ContactForm

# Create your views here.

def home(request):
    title = 'Welcome'
    form = SignUpForm(request.POST or None)
    context = {
        "title": title,
        "form" : form
    }
    if form.is_valid():
        #form.save()
        #print (request.POST['email'])
        instance = form.save(commit = False)
        full_name = form.cleaned_data.get("full_name")
        if not full_name:
            full_name = "New full name"
        instance.full_name = full_name
        # if instance.full_name == None:
        #     instance.full_name == "Guest"
        instance.save()
        context = {
            "title" : "Спасибо за регистрацию."
        }
    return render(request, "home.html", context)



def contact(request):
    title = 'Обратная связь'
    title_align_center = True
    form = ContactForm(request.POST or None)
    if form.is_valid():
        for key, value in form.cleaned_data.items():
            print (key, value)
            #print(form.cleaned_data.get(key))
        # email = form.cleaned_data.get("email")
        # message = form.cleaned_data.get("message")
        # full_name = form.cleaned_data.get("full_name")
        # print(email, message, full_name)

    context = {
        "form" : form,
        "title" : title,
        "title_align_center" : title_align_center
    }
    return render(request, "forms.html", context)

def ourcontact(request):
    return render(request, 'ourcontact.html', {})

def about(request):
    return render(request, 'about.html', {})
def productsnservices(request):
    return render(request, 'productsnservices.html', {})

trydjango18/views.py
from django.shortcuts import render


# Create your views here.

def about(request):

    return render(request, "about.html", {})

templates/about.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}О компании|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

templates/example_fluid.html
{% extends "base.html" %}

{% block jumbotron %}
{% endblock %}



{% block content %}
    <div class="row">
        <div class="col-xs-10" style="background-color: orange">


            .col-md-4


        </div>
    </div>



    <div class="row">
        <div class="col-md-8 col-sm-3" style="background-color: red">.col-md-8
            <div class="row">
                <div class="col-md-6 col-sm-8 col-xm-2" style="background-color: orange">


                    .col-md-4


                </div>
                <div class="col-md-6 col-sm-4 col-xm-10" style="background-color: yellow">.col-md-4</div>
            </div>
        </div>
        <div class="col-md-4 col-sm-3" style="background-color: blue">.col-md-4
            <div class="row">
                <div class="col-md-12" style="background-color: purple">.col-md-4</div>
            </div>
        </div>
    </div>
    {% comment %}<div class="row">
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
    <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
    <div class="col-md-6">.col-md-6</div>
    <div class="col-md-6">.col-md-6</div>
</div>{% endcomment %}
{% endblock %}

templates/forms.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Обратная связь|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            {% if title %}
                <h1 class="{% if title_align_center %}text-align-center{% endif %}">{{ title }}  </h1>
            {% endif %}
            <form method='POST' action=''>{% csrf_token %}
                {{ form| crispy }}
                <input class='btn btn-default' type='submit' value='Submit'/>
            </form>
        </div>
    </div>
{% endblock %}
{% comment %}
<div class="input-group"> example
    <span class="input-group-addon">@</span>
    <input type="text" class="form-control" placeholder="Example">
</div>
<hr>
<div id="div_id_full_name" class="control-group">
    <label for="id_full_name" class="control-label ">Full name</label>
    <div class="controls">
        <input class="form-control" id="id_full_name" name="full_name" type="text">
    </div>
</div>
<div id="div_id_email" class="control-group error">
    <label for="id_email" class="control-label requiredField">Email<span class="asteriskField">*</span>
    </label>
    <div class="controls">
        <input class="form-control" id="id_email" name="email" type="email">
        <p id="error_1_id_email" class="help-block"><strong>Обязательное поле.</strong></p>
    </div>
</div>
<div id="div_id_message" class="control-group">
    <label for="id_message" class="control-label requiredField">Message<span
            class="asteriskField">*</span> </label>
    <div class="controls">
        <input class="form-control" id="id_message" name="message" type="text">
    </div>
</div>
<hr>{% endcomment %}

templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %} | Головна{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

<style>
    {% block style %}

    {%  endblock %}
</style>


{% block jumbotron %}
    <div class="jumbotron">

        <div class="row">
            <div class="col-sm-6">
                <h1>Тестовая страница</h1>
                <p>The MVP Landing project is designed to get your project started. The goal is to help you launch as
                    soon
                    as possible with the least amount of investment using time or money. Join Us today.</p>
                <p>
                    <a class="btn btn-sm btn-primary" href="" role="button">Join US &raquo;</a>
                </p>
            </div>
            <div class="col-sm-6" {% comment %}style="background-color: black;{% endcomment %} height: 320px;">
{#                <img src="{% static "my_app/максимет-черный-лом-погрузка.jpg" %}" alt="My image"/>#}
{#                <img class="container-fluid" src="{% static "img/максимет-черный-лом-погрузка.jpg" %}" hspace="" vspace="10" width="500" height="300" alt="максимет-черный-лом-погрузка">#}
                <img class="container-fluid" src="{% static "img/vgif-ru-23843.gif" %}" hspace="" vspace="10" width="500" height="300" alt="максимет-черный-лом-погрузка">

            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-3 pull-right">
            <p class="lead">Место для контента{% comment %}{{ title }}{% endcomment %}</p>
            {% comment %}<form method='POST' action=''>{% csrf_token %}
                {{ form| crispy }}
                <input class="btn btn-sm btn-primary" type='submit' value='Sign Up'/>
            </form>{% endcomment %}
        </div>
        <div class="col-sm-3 ">
            <p class='lead text-align-center text-14px'> Built with Django &amp; Bootstrap</p>
        </div>
        <div class="col-sm-3">
            <p class='lead text-align-center text-14px'> Create for Starters of all kinds. </p>
        </div>
        <div class="col-sm-3">
            <p class='lead text-align-center text-14px'> Always Open Source</p>
        </div>

    </div>
{% endblock %}

templates/m_about.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}О компании|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

templates/m_head_css.html
{% load staticfiles %}


<!-- Bootstrap core CSS -->
{#        <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">#}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{#    <img src="{% static "my_app/myexample.jpg" %}" alt="My image"/>#}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">



<!-- Custom styles for this template -->
{#        <link href="navbar-static-top.css" rel="stylesheet">#}
<link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">

{#Мой файл CSS#}
<link href="{% static 'css/custom.css' %}" rel="stylesheet">



<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>-->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

templates/m_home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Главная|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

<style>
    {% block style %}

    {%  endblock %}
</style>


{% block jumbotron %}
    <div class="jumbotron">

        <div class="row">
            <div class="col-sm-6">
                <h1>Тестовая страница</h1>
                <p>The MVP Landing project is designed to get your project started. The goal is to help you launch as
                    soon
                    as possible with the least amount of investment using time or money. Join Us today.</p>
                <p>
                    <a class="btn btn-sm btn-primary" href="" role="button">Join US &raquo;</a>
                </p>
            </div>
            <div class="col-sm-6" {% comment %}style="background-color: black;{% endcomment %} height: 320px;">
{#                <img src="{% static "my_app/максимет-черный-лом-погрузка.jpg" %}" alt="My image"/>#}
{#                <img class="container-fluid" src="{% static "img/максимет-черный-лом-погрузка.jpg" %}" hspace="" vspace="10" width="500" height="300" alt="максимет-черный-лом-погрузка">#}
                <img class="container-fluid" src="{% static "img/vgif-ru-23843.gif" %}" hspace="" vspace="10" width="500" height="300" alt="максимет-черный-лом-погрузка">

            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-3 pull-right">
            <p class="lead">Место для контента{% comment %}{{ title }}{% endcomment %}</p>
            {% comment %}<form method='POST' action=''>{% csrf_token %}
                {{ form| crispy }}
                <input class="btn btn-sm btn-primary" type='submit' value='Sign Up'/>
            </form>{% endcomment %}
        </div>
        <div class="col-sm-3 ">
            <p class='lead text-align-center text-14px'> Built with Django &amp; Bootstrap</p>
        </div>
        <div class="col-sm-3">
            <p class='lead text-align-center text-14px'> Create for Starters of all kinds. </p>
        </div>
        <div class="col-sm-3">
            <p class='lead text-align-center text-14px'> Always Open Source</p>
        </div>

    </div>
{% endblock %}

templates/m_javascript.html
{% load staticfiles %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
{#    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

templates/m_navbar.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Компания Максимет</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'productsnservices' %}">ТОВАРЫ И УСЛУГИ</a></li>
                <li><a href="{% url 'about' %}">О КОМПАНИИ</a></li>
                <li><a href="{% url 'ourcontact' %}">КОНТАКТЫ</a></li>
                <li><a href="{% url 'contact' %}">ОБРАТНАЯ СВЯЗЬ</a></li>

                {#                <li class="dropdown">#}
                {#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"#}
                {#                       aria-expanded="false">Dropdown <span class="caret"></span></a>#}
                {#                    <ul class="dropdown-menu">#}
                {#                        <li><a href="#">Action</a></li>#}
                {#                        <li><a href="#">Another action</a></li>#}
                {#                        <li><a href="#">Something else here</a></li>#}
                {#                        <li role="separator" class="divider"></li>#}
                {#                        <li class="dropdown-header">Nav header</li>#}
                {#                        <li><a href="#">Separated link</a></li>#}
                {#                        <li><a href="#">One more separated link</a></li>#}
                {#                    </ul>#}
                {#                </li>#}
            </ul>

{#            КНОПКА РЕГИСТРАЦИИ#}
{#            <ul class="nav navbar-nav navbar-right">#}
{#                {% if request.user.is_authenticated %}#}
{#                    <li><a href="{% url 'auth_logout' %}">Выйти</a></li>#}
{#                {% else %}#}
{#                    <form class="navbar-form navbar-right" method="POST" action="">{% csrf_token %}#}
{#                        <div class="form-group">#}
{#                            <input type="text" class="form-control" name="username" placeholder="Username"/>#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <input type="password" class="form-control" name="password" placeholder="Pasword"/>#}
{#                        </div>#}
{#                        <button type="submit" class="btn btn-default">Войти</button>#}
{#                    </form>#}
                    {#                    <li><a href="{% url 'auth_login' %}">Войти</a></li>#}
{#                    <li><a href="{% url 'registration_register' %}">Регистрация</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
        </div><!--/.nav-collapse -->
    </div>
</nav>

<a href="" title=""></a>

templates/m_ourcontact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Контакты|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

templates/m_productsnservices.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Товары и услуги|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}

templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">Дніпровський Інститут Землеустрою</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'home' %}">Головна</a></li>
                <li><a href="#about">Про нас</a></li>
                <li><a href="#services">Послуги</a></li>
                <li><a href="#portfolio">Портфоліо</a></li>
                <li><a href="#contact">Контакти</a></li>
            </ul>

        </div><!--/.nav-collapse -->
    </div>
</nav>

<a href="" title=""></a>

templates/productsnservices.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}Товары и услуги|{{ block.super }}{% endblock %} {% comment %}Tab's calling{% endcomment %}